### PR TITLE
Document jupyter kernel flags and add compat entires

### PR DESCRIPTION
**Pull request by palday**

### CODE REVIEW

**Comment by dmbates** [comment]
@palday Wouldn't it be better to just add `execute: project` in `_quarto.yml` or add a `metadata.yml`?  I believe that this is equivalent to saying the conversion to `.ipynb` and the jupyter execution of that `.ipynb` file takes place in the project directory and the jupyter execution uses the local `Project.toml` if available.

If at all possible I would like to avoid adding snippets like this to every `.qmd` file.  I am very twitchy these days about cut-and-paste programming.

**Comment by palday** [comment]
I think part of the problem is the following:
> [Julia projects](https://julialang.github.io/IJulia.jl/stable/manual/usage/#Julia-projects)
> 
> The default Jupyter kernel that is installed by IJulia starts with the Julia command line flag --project=@.. A Project.toml (or JuliaProject.toml) in the folder of a notebook (or in a parent folder of this notebook) will therefore automatically become the active project for that notebook. Users that don't want this behavior should install an additional IJulia kernel without that command line flag (see section [Installing additional Julia kernels](https://julialang.github.io/IJulia.jl/stable/manual/installation/#Installing-additional-Julia-kernels)).

For some reason, the kernel I have installed -- which I thought was the default kernel because I don't otherwise use Jupyter/IJulia -- doesn't include this activation step.

In order to fix this, we should probably document adding a kernel that includes this option:

```julia
using IJulia
installkernel("julia", "--project=@.")
```

While we're being fancy, we can also adding threading to the environment:

```julia
julia> installkernel("julia", "--threads=auto", "--project=@.")
[ Info: Installing julia kernelspec in ~/.local/share/jupyter/kernels/julia-1.8
"~/.local/share/jupyter/kernels/julia-1.8"
````

**Comment by dmbates** [comment]
I usually cheat and edit the file `~/.local/share/jupyter/kernels/julia-x.y/kernel.json` to add the `-t<n>` flag.  I find it is easier to edit the configuration file then to figure out from the IJulia documentation what incantation will have the same effect.

**Review by dmbates — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
